### ISSUE TITLE
Horizontal ScrollView

### ISSUE THREAD

**Issue by patelakshay13890** [ayltai/Android-Lib-VerticalMarqueeTextView#1]
How can I use this lib with Horizontal not Vertical Direction..??

**Comment by ayltai** [comment]
You don't need this library for horizontal marquee. The original TextView supports that. You just need to set ellipsize to "marquee", singleLine to "true" and lines to "1". You can refer to [here](http://rajeshandroiddeveloper.blogspot.hk/2013/06/marquee-effect-in-textview-tutorial.html) as an example.

**Comment by patelakshay13890** [comment]
This doesnot work in my case so i need supprt bcoz in my app TextView will
not get focused or Selected for 1 or more sec so this doesnot work in my
case

**Comment by ayltai** [comment]
You can at least have 2 workarounds even if it is not possible to get focused:
1. TextView.setSelected(true), or
2. override TextView, and in TextView.isFocused(), always return true.

**Comment by patelakshay13890** [comment]
can you give some code for this ?

**Comment by ayltai** [comment]
This is not really related to this project. There is a better place for this -> www.stackoverflow.com
Post your code there and show how it doesn't work in the way you like.
