### ISSUE TITLE
Fragment

### ISSUE THREAD

**Issue by vpeace** [ayltai/Android-Lib-VerticalMarqueeTextView#10]
I'M TRYING TO APPLY IT IN A FRAGMENT BUT I'M OT GETTING THE OUTPUT.

**Comment by vpeace** [comment]
If I paste the code in an activity it works but if I paste the same code
inside a fragment it doesn't

**Comment by ayltai** [comment]
**Any sample code for me to reproduce your issue on my end?**

**Comment by vpeace** [comment]
The fragment is present in the viewfinder. There is no error which is
present but the text doesn't just show up.

**Comment by ayltai** [comment]
How can I know what's wrong if you don't provide any code for me to reproduce your problem on my side?

**Comment by ayltai** [comment]
Closing this issue as the reporter refused the provide any relevant code.

**Comment by vpeace** [comment]
I solved the issue. Is there any way I can know that the marquee has ended?
