### ISSUE TITLE
Two VerticalMarqueeTextView

### ISSUE THREAD

**Issue by shastrageek** [ayltai/Android-Lib-VerticalMarqueeTextView#2]
I am try to implement two Marquee in parallel but only first one is working
here is my example layout xml:: 

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:example="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:layout_gravity="center_horizontal"
        android:scaleType="centerInside"
        android:src="@android:drawable/sym_def_app_icon" />
    <android.lib.verticalmarqueetextview.VerticalMarqueeTextView
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:layout_gravity="center_horizontal"
        example:marqueeSpeed="25"
        example:textSize="20dp"
        example:textColor="@android:color/white"
        example:textStyle="bold"
        example:text="The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog." />
   <android.lib.verticalmarqueetextview.VerticalMarqueeTextView
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:layout_gravity="center_horizontal"
        example:marqueeSpeed="25"
        example:textSize="20dp"
        example:textColor="@android:color/white"
        example:textStyle="bold"
        example:text="The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog." />
</LinearLayout>

**Comment by ayltai** [comment]
It works on my phone and emulators. Which Android version you are running?
