### ISSUE TITLE
onEnd : repeate?

### ISSUE THREAD

**Issue by abselt** [ayltai/Android-Lib-VerticalMarqueeTextView#8]

**Comment by ayltai** [comment]
What is your question?

**Comment by abselt** [comment]
Sorry How can I know when the scrollView reached its end so I can repeat the marquee from start again

**Comment by ayltai** [comment]
It automatically repeats scrolling the text when it reaches the end, see https://github.com/ayltai/Android-Lib-VerticalMarqueeTextView/blob/master/VerticalMarqueeTextView/src/main/java/android/lib/widget/verticalmarqueetextview/VerticalMarqueeTextView.java#L466

**Comment by abselt** [comment]
thanks
